//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAPI
{
    using DemoAPI.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demoapiEntities : DbContext
    {
        public demoapiEntities()
            : base("name=demoapiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<owner> owners { get; set; }
        public virtual DbSet<ship> ships { get; set; }
        public DbSet<ShipModel> shipModels { get; set; }
        public virtual DbSet<shipsview> shipsviews { get; set; }
    }
}
