//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public owner()
        {
            this.ships = new HashSet<ship>();
        }
    
        public int owner_id { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public string email { get; set; }
    
        //navigation property to Ships
        //lazy loadin property
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ship> ships { get; set; }
    }
}
